# Generated by Django 5.2.17 on 2026-09-22 13:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('slug', models.SlugField(unique=True, verbose_name='слаг')),
                ('kind', models.CharField(choices=[('rules', 'Правила (сообщения)'), ('chat', 'Чат (сообщения)'), ('glossary', 'Определения'), ('punishments', 'Список наказаний'), ('wheel', 'Колесо'), ('progress', 'Прогресс'), ('achievements', 'Достижения'), ('subsos', 'Подсосы')], default='chat', max_length=16, verbose_name='тип')),
                ('icon', models.CharField(default='#', max_length=8, verbose_name='иконка')),
                ('category', models.CharField(default='ПРОЧЕЕ', max_length=64, verbose_name='категория')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'канал',
                'verbose_name_plural': 'каналы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='имя')),
                ('slug', models.SlugField(unique=True, verbose_name='слаг')),
                ('emoji', models.CharField(default='🙂', max_length=8, verbose_name='эмодзи-аватар')),
                ('color', models.CharField(default='#5865f2', max_length=7, verbose_name='цвет')),
                ('status', models.CharField(blank=True, default='', max_length=128, verbose_name='статус')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'участник',
                'verbose_name_plural': 'участники',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Podsos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='название')),
                ('description', models.TextField(blank=True, default='', verbose_name='описание')),
                ('active', models.BooleanField(default=True, verbose_name='доступен для выбора')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'подсос',
                'verbose_name_plural': 'подсосы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('kind', models.CharField(choices=[('series', 'Сериал / аниме / дорама / мультсериал'), ('movie', 'Фильм / мультфильм'), ('vn', 'Визуальная новелла')], default='series', max_length=10, verbose_name='тип')),
                ('description', models.TextField(blank=True, default='', verbose_name='описание')),
                ('link', models.URLField(blank=True, default='', verbose_name='ссылка')),
                ('episode_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='минут в серии')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='длительность, мин')),
                ('seasons_note', models.CharField(blank=True, default='', max_length=200, verbose_name='заметка о сезонах')),
                ('status', models.CharField(choices=[('proposed', 'Предложено'), ('approved', 'В колесе'), ('archived', 'В архиве')], default='proposed', max_length=10, verbose_name='статус')),
                ('weight', models.PositiveIntegerField(default=10, help_text='Чем меньше, тем реже выпадает (у ВН — малый шанс).', verbose_name='вес в колесе')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'наказание',
                'verbose_name_plural': 'наказания',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=32, unique=True, verbose_name='короткое имя (напр. «ос»)')),
                ('title', models.CharField(max_length=200, verbose_name='полное название')),
                ('definition', models.TextField(blank=True, default='', verbose_name='определение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'термин',
                'verbose_name_plural': 'термины',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FridaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='дата')),
                ('title', models.CharField(blank=True, default='', max_length=120, verbose_name='название')),
                ('tiktoks', models.PositiveIntegerField(default=0, verbose_name='тиктоков в сборке (т)')),
                ('laughs', models.PositiveIntegerField(default=0, verbose_name='очки смеха (ос)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='заметки')),
                ('held', models.BooleanField(default=True, verbose_name='мероприятие проведено')),
                ('extra_podsos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.podsos', verbose_name='выбранный подсос')),
            ],
            options={
                'verbose_name': 'мероприятие',
                'verbose_name_plural': 'мероприятия',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', verbose_name='содержимое')),
                ('pinned', models.BooleanField(default=False, verbose_name='закреплено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.member', verbose_name='автор')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.channel', verbose_name='канал')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spins', models.PositiveIntegerField(default=1, verbose_name='колов (оп)')),
                ('watched_units', models.PositiveIntegerField(default=0, verbose_name='просмотрено единиц')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='заметка')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('progress', 'В процессе'), ('done', 'Отработано')], default='pending', max_length=10, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='отработано')),
                ('punishment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sentences', to='core.punishment', verbose_name='наказание')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='core.fridaysession', verbose_name='мероприятие')),
            ],
            options={
                'verbose_name': 'отработка',
                'verbose_name_plural': 'отработки',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('icon', models.CharField(default='🏆', max_length=8, verbose_name='иконка')),
                ('description', models.TextField(blank=True, default='', verbose_name='описание')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='получено')),
                ('punishment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='core.punishment', verbose_name='наказание')),
                ('sentence', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievement', to='core.sentence', verbose_name='отработка')),
            ],
            options={
                'verbose_name': 'достижение',
                'verbose_name_plural': 'достижения',
                'ordering': ['-unlocked_at', '-id'],
            },
        ),
    ]
